### ISSUE TITLE
Issue with database name with "\"

### ISSUE THREAD

**Issue by ledikari** [d6t/d6tstack#16]
use a database name with \ 

## no user name and password because Trusted_Connection = yes

> d6tstack.utils.pd_to_mssql(chunk, 'mssql+pymssql://someserver123\data/Comissions', 'dbo.mydb', if_exists="append")

will yield error 

> 
> UserWarning: `.pd_to_mssql()` is experimental, if any problems please raise an issue on https://github.com/d6t/d6tstack/issues or make a pull request
>   warnings.warn('`.pd_to_mssql()` is experimental, if any problems please raise an issue on https://github.com/d6t/d6tstack/issues or make a pull request')
> Traceback (most recent call last):
>   File "src\pymssql.pyx", line 636, in pymssql.connect
>   File "src\_mssql.pyx", line 1957, in _mssql.connect
>   File "src\_mssql.pyx", line 677, in _mssql.MSSQLConnection.__init__
> _mssql.MSSQLDriverException: Connection to the database failed for an unknown reason.

**Comment by DOH-Manada** [comment]
Hopefully you solved this by now, but adding r in front of your string like `r'mssql+pymssql://someserver123\data/Comissions'` might work.
